ALTER TABLE CERTIFICATIONS CONVERT TO CHARACTER SET utf8;
ALTER TABLE COUNTRIES CONVERT TO CHARACTER SET utf8;
ALTER TABLE EDUCATIONS CONVERT TO CHARACTER SET utf8;
ALTER TABLE EXP_ACTIVITIES CONVERT TO CHARACTER SET utf8;
ALTER TABLE EXPERIENCES CONVERT TO CHARACTER SET utf8;
ALTER TABLE GENERAL_DATA CONVERT TO CHARACTER SET utf8;
ALTER TABLE PERSON_COUNTRIES CONVERT TO CHARACTER SET utf8;
ALTER TABLE PERSON_LABELS CONVERT TO CHARACTER SET utf8;
ALTER TABLE QUALIFICATIONS CONVERT TO CHARACTER SET utf8;


ALTER TABLE GENERAL_DATA MODIFY NAME VARCHAR(50) CHARACTER SET utf8;
ALTER TABLE GENERAL_DATA MODIFY SURNAME VARCHAR(50) CHARACTER SET utf8;
